// Host-side tests for the two pure-C modules. No Flipper, no SDK, no hardware:
// `make test` runs these with the system gcc, which is what makes CI able to
// catch a codec divergence on every push.
//
// The short-ID and URI cases come from `vectors.h`, generated by
// `tools/gen_vectors.py` from Almagest's Python `idcodec` package. The NDEF
// memory cases are hand-built here, because the byte layout of a tag is exactly
// the thing a generator would have to assume rather than know.

#include <stdio.h>
#include <string.h>

#include "../src/lib/ndef.h"
#include "../src/lib/ndef_encode.h"
#include "../src/lib/shortid.h"
#include "vectors.h"

static int failures = 0;
static int checks = 0;

#define CHECK(condition, ...)                             \
    do {                                                  \
        checks++;                                         \
        if(!(condition)) {                                \
            failures++;                                   \
            printf("  FAIL %s:%d: ", __FILE__, __LINE__); \
            printf(__VA_ARGS__);                          \
            printf("\n");                                 \
        }                                                 \
    } while(0)

// A valid short ID, taken from the generated vectors.
static const char* const VALID_ID = "JSK3G03N";

static void test_shortid_vectors(void) {
    printf("shortid vectors (%zu cases)\n", sizeof(shortid_vectors) / sizeof(shortid_vectors[0]));
    for(size_t i = 0; i < sizeof(shortid_vectors) / sizeof(shortid_vectors[0]); i++) {
        const ShortIdVector* vector = &shortid_vectors[i];
        char out[SHORTID_SIZE];
        ShortIdError error = shortid_validate(vector->raw, out);

        if(vector->canonical == NULL) {
            CHECK(
                error != ShortIdOk,
                "%s should have been rejected, got %s",
                vector->raw,
                error == ShortIdOk ? out : "?");
        } else {
            CHECK(
                error == ShortIdOk,
                "%s should have been accepted, got %s",
                vector->raw,
                shortid_error_text(error));
            if(error == ShortIdOk) {
                CHECK(
                    strcmp(out, vector->canonical) == 0,
                    "%s normalised to %s, expected %s",
                    vector->raw,
                    out,
                    vector->canonical);
            }
        }
    }
}

static void test_shortid_error_reasons(void) {
    printf("shortid error reasons\n");
    char out[SHORTID_SIZE];
    CHECK(shortid_validate("", out) == ShortIdErrEmpty, "empty string");
    CHECK(shortid_validate("   ", out) == ShortIdErrEmpty, "whitespace only");
    CHECK(shortid_validate(NULL, out) == ShortIdErrEmpty, "NULL");
    CHECK(shortid_validate("JSK3G03", out) == ShortIdErrLength, "too short");
    CHECK(shortid_validate("JSK3G03NN", out) == ShortIdErrLength, "too long");
    // `U` is excluded from the alphabet rather than folded into `V`, so it is a
    // bad symbol and must not be silently accepted as something else.
    CHECK(shortid_validate("JSK3G03U", out) == ShortIdErrAlphabet, "U is not in the alphabet");
    CHECK(shortid_validate("JSK3G03!", out) == ShortIdErrAlphabet, "punctuation");
    CHECK(shortid_validate("JSK3G03M", out) == ShortIdErrCheck, "wrong check symbol");
}

static void test_shortid_out_untouched_on_failure(void) {
    printf("shortid leaves the output alone when it fails\n");
    char out[SHORTID_SIZE];
    memcpy(out, "SENTINEL", 9);
    CHECK(shortid_validate("nonsense", out) != ShortIdOk, "should fail");
    CHECK(strcmp(out, "SENTINEL") == 0, "output was clobbered: %s", out);
}

static void test_check_value_catches_human_errors(void) {
    // The two properties the mod-37 check exists for. Asserted directly rather
    // than trusted, because the whole point of the check symbol is that a
    // mistyped or transposed code never resolves to a different real object.
    printf("check symbol catches single-symbol and transposition errors\n");
    static const char ALPHABET[] = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
    char data[SHORTID_DATA_SYMBOLS + 1];
    memcpy(data, VALID_ID, SHORTID_DATA_SYMBOLS);
    data[SHORTID_DATA_SYMBOLS] = '\0';
    unsigned expected = shortid_check_value(data);

    for(size_t position = 0; position < SHORTID_DATA_SYMBOLS; position++) {
        for(size_t symbol = 0; symbol < 32; symbol++) {
            if(ALPHABET[symbol] == data[position]) continue;
            char mutated[SHORTID_DATA_SYMBOLS + 1];
            memcpy(mutated, data, sizeof(mutated));
            mutated[position] = ALPHABET[symbol];
            CHECK(
                shortid_check_value(mutated) != expected,
                "single-symbol change %s -> %s kept the same check value",
                data,
                mutated);
        }
    }

    for(size_t position = 0; position + 1 < SHORTID_DATA_SYMBOLS; position++) {
        if(data[position] == data[position + 1]) continue;
        char mutated[SHORTID_DATA_SYMBOLS + 1];
        memcpy(mutated, data, sizeof(mutated));
        mutated[position] = data[position + 1];
        mutated[position + 1] = data[position];
        CHECK(
            shortid_check_value(mutated) != expected,
            "transposition %s -> %s kept the same check value",
            data,
            mutated);
    }
}

static void test_format_display(void) {
    printf("display formatting\n");
    char display[SHORTID_DISPLAY_SIZE];
    shortid_format_display(VALID_ID, display);
    CHECK(strcmp(display, "JSK3-G03N") == 0, "formatted as %s", display);
}

static void test_uri_vectors(void) {
    printf("uri vectors (%zu cases)\n", sizeof(ndef_url_vectors) / sizeof(ndef_url_vectors[0]));
    for(size_t i = 0; i < sizeof(ndef_url_vectors) / sizeof(ndef_url_vectors[0]); i++) {
        const NdefUrlVector* vector = &ndef_url_vectors[i];
        char out[SHORTID_SIZE];
        bool found = ndef_short_id_from_uri(vector->url, out);

        if(vector->short_id == NULL) {
            CHECK(!found, "%s should carry no short id, got %s", vector->url, found ? out : "?");
        } else {
            CHECK(found, "%s should carry %s, got nothing", vector->url, vector->short_id);
            if(found) {
                CHECK(
                    strcmp(out, vector->short_id) == 0,
                    "%s gave %s, expected %s",
                    vector->url,
                    out,
                    vector->short_id);
            }
        }
    }
}

// Build the user memory of a Type 2 tag holding one Well Known URI record.
// `prefix_code` is the NDEF URI abbreviation index (0x04 is `https://`).
static size_t build_uri_tag(uint8_t* buffer, size_t size, uint8_t prefix_code, const char* body) {
    size_t body_length = strlen(body);
    size_t payload_length = body_length + 1; // the prefix code byte
    size_t record_length = 1 /* header */ + 1 /* type length */ + 1 /* payload length */ +
                           1 /* type 'U' */ + payload_length;
    size_t total = 2 /* TLV tag + length */ + record_length + 1 /* terminator */;
    if(total > size) return 0;

    size_t offset = 0;
    buffer[offset++] = 0x03; // NDEF message TLV
    buffer[offset++] = (uint8_t)record_length;
    buffer[offset++] = 0xD1; // MB | ME | SR, TNF = Well Known
    buffer[offset++] = 0x01; // type length
    buffer[offset++] = (uint8_t)payload_length;
    buffer[offset++] = 'U';
    buffer[offset++] = prefix_code;
    memcpy(buffer + offset, body, body_length);
    offset += body_length;
    buffer[offset++] = 0xFE; // terminator TLV
    return offset;
}

static void test_ndef_memory_happy_path(void) {
    printf("ndef memory, well-formed tag\n");
    uint8_t memory[144] = {0};
    size_t size = build_uri_tag(memory, sizeof(memory), 0x04, "almagest.lan/s/JSK3-G03N");
    CHECK(size > 0, "fixture did not fit");

    char uri[NDEF_URI_MAX];
    CHECK(ndef_find_uri(memory, sizeof(memory), uri, sizeof(uri)), "no uri found");
    CHECK(strcmp(uri, "https://almagest.lan/s/JSK3-G03N") == 0, "expanded to %s", uri);

    char short_id[SHORTID_SIZE];
    CHECK(ndef_short_id_from_memory(memory, sizeof(memory), short_id), "no short id");
    CHECK(strcmp(short_id, VALID_ID) == 0, "got %s", short_id);
}

static void test_ndef_memory_prefix_codes(void) {
    printf("ndef memory, every prefix code we accept\n");
    struct {
        uint8_t code;
        const char* body;
    } cases[] = {
        {0x00, "https://almagest.lan/s/JSK3-G03N"},
        {0x03, "almagest.lan/s/JSK3-G03N"},
        {0x04, "almagest.lan/s/JSK3-G03N"},
        {0x02, "almagest.lan/s/JSK3-G03N"}, // https://www.
    };
    for(size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        uint8_t memory[144] = {0};
        build_uri_tag(memory, sizeof(memory), cases[i].code, cases[i].body);
        char short_id[SHORTID_SIZE];
        CHECK(
            ndef_short_id_from_memory(memory, sizeof(memory), short_id),
            "prefix code 0x%02X failed",
            cases[i].code);
    }
}

static void test_ndef_memory_rejects(void) {
    printf("ndef memory, malformed and irrelevant tags\n");
    char short_id[SHORTID_SIZE];

    // A factory-fresh NDEF-formatted but empty tag: an NDEF TLV of length 0.
    uint8_t empty[] = {0x03, 0x00, 0xFE, 0x00, 0x00, 0x00};
    CHECK(!ndef_short_id_from_memory(empty, sizeof(empty), short_id), "empty tag");

    // All zeroes: a truly unformatted tag.
    uint8_t zeroes[64] = {0};
    CHECK(!ndef_short_id_from_memory(zeroes, sizeof(zeroes), short_id), "unformatted tag");

    // A text record, not a URI record.
    uint8_t text[] = {0x03, 0x0B, 0xD1, 0x01, 0x07, 'T', 0x02, 'e', 'n', 'h', 'i', 0x00, 0xFE};
    CHECK(!ndef_short_id_from_memory(text, sizeof(text), short_id), "text record");

    // A URI record whose length runs off the end of the buffer — a truncated
    // read must be refused, never parsed past the end.
    uint8_t truncated[] = {0x03, 0x40, 0xD1, 0x01, 0x3C, 'U', 0x04, 'a', 'l'};
    CHECK(!ndef_short_id_from_memory(truncated, sizeof(truncated), short_id), "truncated");

    // A well-formed URI that is simply not an Almagest tag.
    uint8_t other[144] = {0};
    build_uri_tag(other, sizeof(other), 0x04, "example.com/some/page");
    CHECK(!ndef_short_id_from_memory(other, sizeof(other), short_id), "unrelated url");

    // A URI whose code fails the check symbol — a real risk, since this is
    // exactly what a partially corrupted tag looks like.
    uint8_t corrupt[144] = {0};
    build_uri_tag(corrupt, sizeof(corrupt), 0x04, "almagest.lan/s/JSK3-G03M");
    CHECK(!ndef_short_id_from_memory(corrupt, sizeof(corrupt), short_id), "bad check symbol");

    // An unknown URI prefix code must be refused rather than guessed at.
    uint8_t unknown_prefix[144] = {0};
    build_uri_tag(unknown_prefix, sizeof(unknown_prefix), 0x1F, "almagest.lan/s/JSK3-G03N");
    CHECK(!ndef_short_id_from_memory(unknown_prefix, sizeof(unknown_prefix), short_id), "prefix");
}

static void test_ndef_memory_skips_leading_null_tlvs(void) {
    printf("ndef memory, NULL TLV padding before the message\n");
    uint8_t memory[144] = {0};
    memory[0] = 0x00; // NULL TLV
    memory[1] = 0x00;
    size_t written =
        build_uri_tag(memory + 2, sizeof(memory) - 2, 0x04, "almagest.lan/s/JSK3-G03N");
    CHECK(written > 0, "fixture did not fit");
    char short_id[SHORTID_SIZE];
    CHECK(ndef_short_id_from_memory(memory, sizeof(memory), short_id), "not found past padding");
}

// ---------------------------------------------------------------------------
// The encoder — ADR 0013. Antlia can write a tag in bridge mode, so these bytes
// must be the same bytes `deviceagent/agent/ndef.py` writes.
// ---------------------------------------------------------------------------

static void test_encode_vectors_match_the_python_encoder(void) {
    size_t count = sizeof(ndef_encode_vectors) / sizeof(ndef_encode_vectors[0]);
    printf("ndef encode vectors: %zu cases\n", count);

    for(size_t i = 0; i < count; i++) {
        const NdefEncodeVector* vector = &ndef_encode_vectors[i];
        uint8_t out[NDEF_ENCODE_MAX];
        size_t written = 0;

        CHECK(
            ndef_build_uri_image(vector->uri, out, sizeof(out), &written),
            "encoder refused a URI the Python encoder accepted");
        CHECK(written == vector->size, "image length differs from the Python encoder");
        CHECK(
            memcmp(out, vector->image, vector->size) == 0,
            "image bytes differ from the Python encoder");

        size_t pages = 0;
        CHECK(
            ndef_uri_page_count(vector->uri, NDEF_NTAG213_USER_PAGES, &pages), "page count");
        CHECK(pages == vector->pages, "page count differs from the Python encoder");
    }
}

static void test_encode_round_trips_through_this_app_s_own_decoder(void) {
    printf("ndef encode round trip through ndef_short_id_from_memory\n");
    // Not redundant with the vectors above: those prove Antlia agrees with the
    // *other* implementation. This proves it agrees with itself — that a tag
    // Antlia writes is one Antlia can read, which is what the read-back after a
    // write actually asks.
    size_t count = sizeof(ndef_encode_vectors) / sizeof(ndef_encode_vectors[0]);
    for(size_t i = 0; i < count; i++) {
        const char* uri = ndef_encode_vectors[i].uri;
        uint8_t memory[NDEF_ENCODE_MAX];
        size_t written = 0;
        CHECK(ndef_build_uri_image(uri, memory, sizeof(memory), &written), "build");

        char read_back[NDEF_URI_MAX];
        CHECK(ndef_find_uri(memory, written, read_back, sizeof(read_back)), "not found");
        CHECK(strcmp(read_back, uri) == 0, "round trip changed the URI");
    }
}

static void test_encode_refuses_rather_than_truncating(void) {
    printf("ndef encode refusals\n");
    uint8_t out[NDEF_ENCODE_MAX];
    size_t written = 0;

    CHECK(!ndef_build_uri_image("", out, sizeof(out), &written), "empty URI");
    CHECK(!ndef_build_uri_image(NULL, out, sizeof(out), &written), "NULL URI");

    // A control byte means the caller is about to write something that is not a
    // URI, and the tag would read back as garbage this app's own decoder
    // refuses. Better to fail where the cause is still attached.
    CHECK(!ndef_build_uri_image("https://x/\n", out, sizeof(out), &written), "control byte");

    // A buffer too small must not produce a partial image.
    uint8_t tiny[8];
    CHECK(
        !ndef_build_uri_image(
            "https://almagest.lan/s/JSK3G03N", tiny, sizeof(tiny), &written),
        "small buffer");

    // **The important one.** A Type 2 Tag write has no transaction, so running
    // off the end of the tag leaves the earlier pages committed. Refusing on the
    // page count, before a byte is written, is what keeps a too-long payload
    // from producing a half-written tag.
    size_t pages = 0;
    CHECK(
        !ndef_uri_page_count("https://almagest.lan/s/JSK3G03N", 4, &pages),
        "a payload that does not fit must be refused");
}

static void test_encode_prefers_the_longest_abbreviation(void) {
    printf("ndef encode longest-match abbreviation\n");
    // `https://www.x` matches both `https://` (0x04) and `https://www.` (0x02).
    // Picking the shorter one still decodes correctly, which is exactly why it
    // would go unnoticed — and would not be the bytes the Python encoder wrote.
    uint8_t out[NDEF_ENCODE_MAX];
    size_t written = 0;
    CHECK(
        ndef_build_uri_image("https://www.almagest.lan/s/JSK3G03N", out, sizeof(out), &written),
        "build");
    CHECK(out[6] == 0x02, "expected the https://www. identifier code");
}

int main(void) {
    test_shortid_vectors();
    test_shortid_error_reasons();
    test_shortid_out_untouched_on_failure();
    test_check_value_catches_human_errors();
    test_format_display();
    test_uri_vectors();
    test_ndef_memory_happy_path();
    test_ndef_memory_prefix_codes();
    test_ndef_memory_rejects();
    test_ndef_memory_skips_leading_null_tlvs();
    test_encode_vectors_match_the_python_encoder();
    test_encode_round_trips_through_this_app_s_own_decoder();
    test_encode_refuses_rather_than_truncating();
    test_encode_prefers_the_longest_abbreviation();

    printf("\n%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
