"""Generate `tests/vectors.h` from Almagest's Python `idcodec` package.

The C codec in `src/lib/shortid.c` is a port, and a port can drift. When it does,
the failure is nasty and quiet: a tag the API wrote reads as corrupt on the
Flipper, or — far worse — a corrupted code passes the check symbol on one side
and not the other, and a wrong ID gets typed into an inventory system. So the
expectations are not written by hand here; every case is run through the real
Python implementation and asserted before it is emitted.

Run from the `idcodec` directory so its package is importable:

    make vectors

which is `cd ../idcodec && uv run python ../antlia/tools/gen_vectors.py`.
"""

from __future__ import annotations

import random

from idcodec.shortid import ALPHABET, InvalidShortId, generate, validate
from idcodec.tagpayload import parse_ndef_url

# Fixed so the generated header is stable and a regeneration produces no diff
# unless the codec's behaviour actually changed.
SEED = 20260730
VALID_COUNT = 96


def c_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def c_optional_string(text: str | None) -> str:
    return "NULL" if text is None else c_string(text)


def short_id_cases(valid: list[str], rng: random.Random) -> list[tuple[str, str | None]]:
    cases: list[tuple[str, str | None]] = []

    for code in valid:
        cases.append((code, code))
        cases.append((f"{code[:4]}-{code[4:]}", code))
        cases.append((code.lower(), code))

    # The O/I/L confusions are folded; U is not, because it is excluded from the
    # alphabet rather than merged into another symbol.
    for code in valid[:20]:
        swapped = code.replace("0", "O", 1).replace("1", "I", 1)
        if swapped != code:
            cases.append((swapped, code))

    # A cosmetic display prefix is tolerated, not parsed.
    for code in valid[:10]:
        cases.append((f"BIN {code[:4]}-{code[4:]}", code))

    # Whitespace used as the group separator means the whole string.
    for code in valid[:10]:
        cases.append((f"{code[:4]} {code[4:]}", code))

    # The check symbol itself is wrong.
    for code in valid[:30]:
        data, check = code[:7], code[7]
        cases.append((data + next(a for a in ALPHABET if a != check), None))

    # One data symbol is wrong — the first error class mod 37 must catch.
    for code in valid[:30]:
        position = rng.randrange(7)
        replacement = next(a for a in ALPHABET if a != code[position])
        cases.append((code[:position] + replacement + code[position + 1 :], None))

    # Two adjacent symbols are swapped — the second error class.
    for code in valid[:30]:
        for position in range(6):
            if code[position] != code[position + 1]:
                cases.append(
                    (
                        code[:position]
                        + code[position + 1]
                        + code[position]
                        + code[position + 2 :],
                        None,
                    )
                )
                break

    # Malformed shapes.
    cases.extend(
        (bad, None)
        for bad in ("", "   ", "4K7T", "4K7T-92M88", "4K7T-92MU", "4K7T-92M!", "ZZZZZZZZZ")
    )
    return cases


def uri_cases(valid: list[str]) -> list[str]:
    urls: list[str] = []
    for code in valid[:12]:
        grouped = f"{code[:4]}-{code[4:]}"
        # The host is deliberately varied: the rule is host-agnostic, because a
        # rename must not invalidate every tag already written.
        urls.append(f"https://almagest.lan/s/{grouped}")
        urls.append(f"https://almagest.lan/s/{code}")
        urls.append(f"http://10.0.0.5:8000/s/{grouped}")
        urls.append(f"https://almagest.lan/s/{grouped}/")
        urls.append(f"https://other-host.example/s/{code.lower()}")
    urls.extend(
        [
            "https://almagest.lan/",
            "https://almagest.lan/s/",
            "https://almagest.lan/s/NOTACODE",
            "https://almagest.lan/parts/4K7T-92M8",
            "https://almagest.lan/s/4K7T-92M8/extra",
            "tel:+15551234",
            "",
        ]
    )
    return urls


def main() -> None:
    rng = random.Random(SEED)
    valid = [generate(rng.getrandbits) for _ in range(VALID_COUNT)]

    lines = [
        "// GENERATED by tools/gen_vectors.py from the Python `idcodec` package.",
        "// Do not edit by hand — run `make vectors`.",
        "//",
        "// These vectors are the contract between the two implementations. The C codec",
        "// must agree with the Python one symbol for symbol, or a tag the API wrote is",
        "// unreadable by the Flipper.",
        "#pragma once",
        "",
        "typedef struct {",
        "    const char* raw;",
        "    const char* canonical; // NULL when the input must be rejected",
        "} ShortIdVector;",
        "",
        "static const ShortIdVector shortid_vectors[] = {",
    ]

    seen: set[str] = set()
    for raw, expected in short_id_cases(valid, rng):
        if raw in seen:
            continue
        seen.add(raw)
        try:
            actual: str | None = validate(raw)
        except InvalidShortId:
            actual = None
        assert actual == expected, f"vector disagrees with idcodec: {raw!r} {expected!r} {actual!r}"
        lines.append(f"    {{{c_string(raw)}, {c_optional_string(expected)}}},")

    lines += [
        "};",
        "",
        "typedef struct {",
        "    const char* url;",
        "    const char* short_id; // NULL when the URL carries no usable short id",
        "} NdefUrlVector;",
        "",
        "static const NdefUrlVector ndef_url_vectors[] = {",
    ]

    for url in uri_cases(valid):
        lines.append(f"    {{{c_string(url)}, {c_optional_string(parse_ndef_url(url))}}},")

    # No trailing blank line: clang-format strips one, and `ufbt format` runs over
    # this directory — so emitting one would make the generated file differ from a
    # freshly generated one the moment anybody formatted the tree.
    lines.append("};")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
